# Generated by Django 6.0.3 on 2026-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_addres_user_city_user_document_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comissão'),
        ),
    ]
