# Generated by Django 6.0.3 on 2026-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Comissão'),
        ),
    ]
