# Generated by Django 6.0.3 on 2026-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Documento'),
        ),
    ]
