# Generated by Django 6.1 on 2026-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
