# Generated by Django 6.1 on 2026-08-20 12:23

import django.db.models.deletion
import utils.encrypted_fields.char_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=utils.encrypted_fields.char_field.EncryptedCharField(blank=True, max_length=15, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=utils.encrypted_fields.char_field.EncryptedCharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', utils.encrypted_fields.char_field.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('number', utils.encrypted_fields.char_field.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('neighborhood', utils.encrypted_fields.char_field.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('complemento', utils.encrypted_fields.char_field.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
    ]
