# Generated by Django 6.1 on 2026-08-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_addres_remove_user_cep_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='complemento',
            new_name='complement',
        ),
    ]
