# Generated by Django 6.1 on 2026-08-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_complemento_address_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
