# Generated by Django 6.0.3 on 2026-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipsale',
            name='service',
            field=models.BooleanField(default=False, verbose_name='Teve cadastro?'),
        ),
    ]
