# Generated by Django 6.0.3 on 2026-05-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0002_chipsale_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChipSale',
        ),
    ]
