# Generated by Django 6.0.3 on 2026-05-13 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_alter_promoterstock_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(help_text='Número de série único impresso no chip físico', max_length=25, unique=True, verbose_name='ICCID do Chip')),
                ('service', models.BooleanField(default=False, verbose_name='Teve cadastro?')),
                ('customer_name', models.CharField(blank=True, default=None, max_length=255, verbose_name='Nome completo do cliente')),
                ('customer_cpf', models.CharField(blank=True, default=None, help_text='Ex: 000.000.000-00', max_length=14, verbose_name='CPF do cliente')),
                ('customer_birth_date', models.DateField(blank=True, default=None, verbose_name='Data de nascimento')),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Chip na venda')),
                ('service_fee_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Serviço na venda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.promoterstock', verbose_name='Chip (Produto)')),
                ('promoter', models.ForeignKey(limit_choices_to={'type': 'promoter'}, on_delete=django.db.models.deletion.PROTECT, related_name='chip_sales', to=settings.AUTH_USER_MODEL, verbose_name='Promotor')),
            ],
            options={
                'verbose_name': 'venda de chip',
                'verbose_name_plural': 'vendas de chips',
                'ordering': ['-created_at'],
            },
        ),
    ]
