# Generated by Django 6.0.3 on 2026-05-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsale',
            name='customer_birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='chipsale',
            name='customer_cpf',
            field=models.CharField(blank=True, default=None, help_text='Ex: 000.000.000-00', max_length=14, null=True, verbose_name='CPF do cliente'),
        ),
        migrations.AlterField(
            model_name='chipsale',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome completo do cliente'),
        ),
    ]
