# Generated by Django 6.0.3 on 2026-05-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_promoterstock_product'),
        ('sales', '0002_alter_chipsale_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsale',
            name='product',
            field=models.ForeignKey(limit_choices_to={'quantity__gt': 0}, on_delete=django.db.models.deletion.PROTECT, to='inventory.promoterstock', verbose_name='Chip (Produto)'),
        ),
    ]
