# Generated by Django 6.0.3 on 2026-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_ordersale_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersale',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade total de itens'),
        ),
        migrations.AddField(
            model_name='ordersale',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor total'),
        ),
    ]
