# Generated by Django 6.0.3 on 2026-05-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_ordersale_total_quantity_ordersale_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersale',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='ordersale',
            name='total_value',
        ),
    ]
