# Generated by Django 6.0.3 on 2026-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_ordersale_total_quantity_ordersale_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersale',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('cash', 'Dinheiro')], default='pix', max_length=20, verbose_name='Método de Pagamento'),
        ),
    ]
