# Generated by Django 6.0.3 on 2026-07-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipsale',
            name='customer_birth_date',
        ),
        migrations.RemoveField(
            model_name='chipsale',
            name='customer_cpf',
        ),
        migrations.RemoveField(
            model_name='chipsale',
            name='customer_name',
        ),
    ]
