# Generated by Django 6.0.3 on 2026-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_chipsale_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersale',
            name='return_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Retorno em'),
        ),
    ]
