# Generated by Django 6.0.3 on 2026-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_ordersale_return_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersale',
            name='return_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de Retorno'),
        ),
    ]
