# Generated by Django 6.0.3 on 2026-04-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Iventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True, verbose_name='Código de barras')),
                ('type', models.CharField(choices=[('acessory', 'Acessório'), ('chip', 'Chip')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=355, null=True, verbose_name='Descrição')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo médio')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de venda')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/covers/%Y/%m/%d/', verbose_name='Imagem')),
                ('in_catalog', models.BooleanField(default=True, verbose_name='Em catálogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Categoria')),
            ],
        ),
    ]
