# Generated by Django 6.0.3 on 2026-04-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iventory',
            new_name='Product',
        ),
    ]
