# Generated by Django 6.0.3 on 2026-05-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em posse')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Venda')),
                ('sale_price_with_service', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço com Serviço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(limit_choices_to={'type': 'chip'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('promoter', models.ForeignKey(limit_choices_to={'type': 'promoter'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estoque do promotor',
                'verbose_name_plural': 'estoques dos promotores',
                'unique_together': {('promoter', 'product')},
            },
        ),
    ]
