# Generated by Django 6.0.3 on 2026-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_promoterstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoterstock',
            name='sale_price_with_service',
        ),
        migrations.AddField(
            model_name='promoterstock',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Serviço'),
        ),
    ]
