# Generated by Django 6.0.3 on 2026-05-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_promoterstock_sale_price_with_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoterstock',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type': 'chip'}, on_delete=django.db.models.deletion.PROTECT, related_name='promoter_stock', to='inventory.product'),
        ),
    ]
