# Generated by Django 6.0.3 on 2026-05-15 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_promoterstock_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoterstock',
            name='promoter',
            field=models.ForeignKey(limit_choices_to={'type__in': ['admin', 'promoter']}, on_delete=django.db.models.deletion.CASCADE, related_name='my_stock', to=settings.AUTH_USER_MODEL),
        ),
    ]
