# Generated by Django 6.0.3 on 2026-07-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_promoterstock_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_min_quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='Quantidade mínima para atacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de atacado'),
        ),
    ]
